Update README.md
TeamLapen/Vampirism pull request #1335
Opened 2024-02-06 13:40 UTC by lunofe

improve readability of licensing

2024-02-06 14:19 UTC, Cheaterpaul requested changes

2024-02-06 14:19 UTC, Cheaterpaul commented on README.md
> +The source code and text in this repository is licenced under [LGPLv3](https://raw.githubusercontent.com/TeamLapen/Vampirism/1.20/CODE_LICENCE) ***except*** for the following parts:
master was the correct branch indicator. It should always redirect to the default branch so we do not need to update this here if we are changing the default branch.

But it is not a bad idea to correct the spelling and name it `CODE_LICENSE`. `https://raw.githubusercontent.com/TeamLapen/Vampirism/master/CODE_LICENSE` should do the trick

2024-02-10 14:51 UTC, maxanier commented on README.md
> +The source code and text in this repository is licenced under [LGPLv3](https://raw.githubusercontent.com/TeamLapen/Vampirism/1.20/CODE_LICENCE) ***except*** for the following parts:
I hate the word LI*EN*E, I always spell it wrong ^^

2024-02-24 14:31 UTC, closed without merging

2024-02-24 16:06 UTC, Cheaterpaul commented
@lunofe should I commit this myself, or do you plan something else?