new hunter action
TeamLapen/Vampirism pull request #394
Opened 2019-03-10 17:47 UTC by Cheaterpaul

new icon and color changeable
disguise overlay now disappear after action ended
#377

2019-03-12 22:00 UTC, maxanier requested changes
Feels awesome to sense those evil vampires :smile: 

I think the radius could be bigger though, maybe twice? Also the color seems almost pink, so maybe it could get a little bit more reddish.

Off topic. Can you branch future PR from the latest master or replace the `import jline.Nullable`  in `SimpleSpawnerLogic` with `javax.Nullable`. Somehow that package has been removed from my setup. Guess it has been removed from Forge

2019-03-12 22:00 UTC, maxanier commented on src/main/resources/assets/vampirism/lang/en_US.lang
> +action.vampirism.hunter.awareness=Awareness
Maybe vampire awareness

2019-03-12 22:00 UTC, maxanier commented on src/main/resources/assets/vampirism/lang/en_US.lang
> +text.vampirism.skill.awareness=Notify if vampire Players or Entities are nearby
Maybe  "Sense nearby vampire players or entities"

2019-03-12 22:00 UTC, maxanier commented on src/main/java/de/teamlapen/vampirism/player/hunter/actions/AwarenessHunterAction.java
> +        List<EntityLivingBase> entities = player.getRepresentingEntity().getEntityWorld().getEntitiesWithinAABB(EntityLivingBase.class, new AxisAlignedBB(player.getRepresentingEntity().posX - Balance
If it is easily possible to avoid creating a new BB every time that would be good, if it isn't feasible, that's fine too.

I think there is a hardcoded 12 left here

2019-03-12 22:00 UTC, maxanier commented on src/main/java/de/teamlapen/vampirism/player/hunter/actions/AwarenessHunterAction.java
> +        if (nearbyVampire(player)) {
Probably better to only update this only every 10 or 20 ticks to reduce load. (player.getRepresentingEntity.ticksExisted%20==0)

2019-03-12 22:00 UTC, maxanier commented on src/main/java/de/teamlapen/vampirism/player/hunter/HunterPlayerSpecialAttribute.java
> +            vampireNearbyTicks++;
Although quite unlikely, the int might overflow. If you cap it to 20 here, you don't have to do it in #getVampireNearbyProgress

2019-03-12 22:00 UTC, maxanier commented on src/main/java/de/teamlapen/vampirism/player/hunter/HunterPlayerSpecialAttribute.java
> +    private boolean vampireNearby = false;
This can probably avoided by using vampireNearbyTicks == 0 instead of this.

2019-03-13 01:42 UTC, Cheaterpaul commented
closed(fail) new on is coming up

2019-03-13 01:42 UTC, closed without merging