replace Skill & Action faction attribute with getter
TeamLapen/Vampirism pull request #710
Opened 2020-06-11 11:44 UTC by Cheaterpaul

2020-06-22 20:18 UTC, Cheaterpaul commented
make sure the changes are binary compatible

2020-06-29 12:44 UTC, maxanier commented
Make sure to tag anything that could be solved in a better way with breaking changes with a `TODO 1.16`

2020-06-29 14:40 UTC, Cheaterpaul commented on src/api/java/de/teamlapen/vampirism/api/entity/factions/IFactionRegistry.java
> +    <T extends IFactionEntity> IFaction registerFaction(ResourceLocation id, Class<T> entityInterface, Color color, boolean hostileTowardsNeutral, @Nullable IVillageFactionData villageFactionData);
could also be handled like the chat color

2020-06-29 14:42 UTC, Cheaterpaul commented on src/api/java/de/teamlapen/vampirism/api/entity/CaptureEntityEntry.java
> +public class CaptureEntityEntry extends WeightedRandom.Item {
could be moved into IVillageFactionData

2020-06-29 14:56 UTC, Cheaterpaul commented on src/api/java/de/teamlapen/vampirism/api/event/VampirismVillageEvent.java
> +        MobEntity oldEntity;
acceptable because the event was never fired

2020-06-29 15:12 UTC, Cheaterpaul commented
Not sure about the events. As you said, if they were never fired, Binary compatibility is not necessary.

2020-06-29 17:49 UTC, maxanier requested changes

2020-06-29 17:49 UTC, maxanier commented on src/api/java/de/teamlapen/vampirism/api/entity/factions/IVillageFactionData.java
> +            return ImmutableList.of();
`Collections.emptyList()`?

2020-06-29 17:49 UTC, maxanier commented on src/api/java/de/teamlapen/vampirism/api/entity/player/actions/DefaultAction.java
> -    public DefaultAction(IPlayableFaction<T> faction) {
This is still breaking.
Keep constructor and `getFaction` method.
Add additional empty constructor, that initializes with null and override `getFaction` in subclass. Add TODO

2020-06-29 17:49 UTC, maxanier commented on src/api/java/de/teamlapen/vampirism/api/entity/player/skills/DefaultSkill.java
> -    }
Same as with the action

2020-07-01 19:59 UTC, merged