Add minion stats and leveling
TeamLapen/Vampirism pull request #761
Opened 2020-08-22 20:57 UTC by maxanier

2020-08-24 20:50 UTC, maxanier commented
Maybe have only 2-3 upgrade variant items which can be used for multiple levels?

2020-08-25 13:50 UTC, Cheaterpaul requested changes

2020-08-25 13:50 UTC, Cheaterpaul commented on src/main/java/de/teamlapen/vampirism/entity/minion/HunterMinionEntity.java
> +                    player.sendStatusMessage(new TranslationTextComponent("text.vampirism.minion.upgraded"), true);
There should be only one of the status messages, because the message in the actionbar (true) can not be read

2020-08-25 13:50 UTC, Cheaterpaul commented on src/main/java/de/teamlapen/vampirism/client/gui/HunterMinionStatsScreen.java
> +        renderStatRow(3, resourceLevel, new StringTextComponent(""), data.getResourceEfficiencyLevel() + 1, HunterMinionEntity.HunterMinionData.MAX_LEVEL_RESOURCES + 1);
add `(int)(Math.ceil((float)(data.getResourceEfficiencyLevel() + 1) / (HunterMinionEntity.HunterMinionData.MAX_LEVEL_RESOURCES + 1) * 100)) + "%")` to the resourceLevel?

2020-08-25 13:50 UTC, Cheaterpaul commented on src/main/java/de/teamlapen/vampirism/client/gui/MinionStatsScreen.java
> +            statButtons.add(this.addButton(new Button(guiLeft + 225, guiTop + 43 + 26 * i, 20, 20, "+", (button) -> VampirismMod.dispatcher.sendToServer(new UpgradeMinionStatPacket(entity.getEntityId
make them invisible on creation.

if the minion is full level the buttons are shown for a brief moment before hiding them

2020-08-25 14:13 UTC, Cheaterpaul commented on src/main/java/de/teamlapen/vampirism/entity/minion/VampireMinionEntity.java
> +
```suggestion

 @OnlyIn(Dist.Client)
```

2020-08-25 14:20 UTC, Cheaterpaul commented
yes maybe reduce the items to 3, but no less so there are still 3 different prices for the items rather than two

2020-08-26 20:21 UTC, merged